#!/usr/bin/ruby
require 'rubygems'
require 'cpee-model-management/implementation'

options = {
  :host => 'localhost',
  :port => 9316,
  :secure => false
}

Riddl::Server.new(CPEE::ModelManagement::SERVER, options) do |opts|
  accessible_description true
  cross_site_xhr true

  use CPEE::ModelManagement::implementation(opts)
end.loop!
