#!/usr/bin/ruby
if File.exist?(File.join(__dir__,'..','lib','cpee-model-management','implementation.rb'))
  require_relative File.join(__dir__,'..','lib','cpee-model-management','implementation')
elsif File.exist?(File.join(Dir.home,'Projects','cpee-model-management','lib','cpee-model-management','implementation.rb'))
  require_relative File.join(Dir.home, 'Projects','cpee-model-management','lib','cpee-model-management','implementation')
else
  require 'cpee-model-management/implementation'
end

options = {
  :host => 'localhost',
  :port => 9316,
  :secure => false
}

Riddl::Server.new(CPEE::ModelManagement::SERVER, options) do |opts|
  accessible_description true
  cross_site_xhr true

  use CPEE::ModelManagement::implementation(opts)
end.loop!
